Add resource-class to offer/lease
CCI-MOC/esi-leap pull request #98
Opened 2022-06-21 17:29 UTC by DanNiESh

2022-06-22 15:36 UTC, tzumainn reviewed
Thinking about it - we may not want to actually store the resource_class field in the esi-leap database, as that's duplication of information. It may be better to fetch it from Ironic, in the same way that we fetch the node name from Ironic (in esi_leap/resource/objects/ironic.py). Take a look and let me know what you think!

2022-06-29 15:00 UTC, tzumainn requested changes
This looks pretty good! Two requested changes inline; let me know if you think those changes wouldn't be possible.

2022-06-29 15:50 UTC, DanNiESh commented on esi_leap/api/controllers/v1/lease.py
> +                    for lease in leases]
Ah, do you mean using one code block for both cases? Sure!

2022-06-29 16:14 UTC, DanNiESh commented on esi_leap/api/controllers/v1/lease.py
> +                    for lease in leases]
Does it look good now?

2022-06-29 17:07 UTC, tzumainn commented on esi_leap/api/controllers/v1/lease.py
> +                    for lease in leases]
Almost! I was thinking something more like (for offers):

````
offers_with_added_info = [Offer(**utils.offer_get_dict_with_added_info(o, project_list, node_list))
                for o in offers]
if resource_class:
  offer_collection.offers = [offer in offers_with_added_info if offer.get('resource_class') == resource_class]
else:
  offer_collection.offers = offers_with_added_info
````

2022-06-29 17:11 UTC, DanNiESh commented on esi_leap/api/controllers/v1/lease.py
> +                    for lease in leases]
Ah, gotcha!

2022-06-29 18:26 UTC, DanNiESh commented on esi_leap/api/controllers/v1/lease.py
> +                    for lease in leases]
Done!

2022-06-30 16:50 UTC, merged